/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

/**
 *
 * @author Кирилл
 */
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class ViewDatabase extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    private String Id;
    private String status;
  
    private void UpdateJTable(){
        String sql="Select * from Cars";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }
    /**
     * Creates new form ViewDatabase
     */
    public ViewDatabase() {
        initComponents();
        DeleteItem.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        currentStatus.setVisible(false);
        statusType.setVisible(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Exit = new javax.swing.JButton();
        FilterType = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtFilterInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        SortType = new javax.swing.JComboBox();
        DeleteItem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        statusType = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        currentStatus = new javax.swing.JTextField();
        Edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Просмотр");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
            },
            new String [] {
                "ID", "Марка", "Модель", "ГодВыпуска",

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Exit.setText("Назад");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        FilterType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Выберите поле", "Марка", "Модель", "ГодВыпуска", "Класс", "ОбъёмДвиг", "Цвет", "Цена", "Статус" }));

        jLabel1.setText("Фильтрация:");

        txtFilterInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterInputKeyReleased(evt);
            }
        });

        jLabel2.setText("Сортировка:");

        SortType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "По умолчанию", "Марка", "Модель", "Год", "ОбъёмДвигателя", "Цвет", "Цена" }));
        SortType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortTypeActionPerformed(evt);
            }
        });

        DeleteItem.setText("Удалить запись");
        DeleteItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteItemMouseClicked(evt);
            }
        });

        jLabel3.setText("Сменить статус:");

        statusType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Продаётся", "Забронирован", "Продан" }));
        statusType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTypeActionPerformed(evt);
            }
        });

        jLabel4.setText("Текущий статус:");

        currentStatus.setEditable(false);

        Edit.setText("Редактировать");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FilterType, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SortType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Edit)))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statusType, 0, 149, Short.MAX_VALUE)
                            .addComponent(currentStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Exit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(statusType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FilterType)
                            .addComponent(txtFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SortType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(currentStatus)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 14, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn = ConnectDatabase.ConnectDB();
        UpdateJTable();
    }//GEN-LAST:event_formWindowOpened

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        new MainWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void txtFilterInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterInputKeyReleased
        // TODO add your handling code here:
        String temp = txtFilterInput.getText() + "%";
        String sql=null;
        if(FilterType.getSelectedIndex()== 1) 
            sql = "select * from Cars where Марка like'"+temp+"'";

        if(FilterType.getSelectedIndex()== 2) 
            sql = "select * from Cars where Модель like'"+temp+"'";

        if(FilterType.getSelectedIndex()== 3) 
            sql = "select * from Cars where ГодВыпуска like'"+temp+"'";

        if(FilterType.getSelectedIndex()== 4) 
            sql = "select * from Cars where Класс like'"+temp+"'";

        if(FilterType.getSelectedIndex()== 5) 
            sql = "select * from Cars where ОбъёмДвигателя like'"+temp+"'";

        if(FilterType.getSelectedIndex()== 6) 
            sql = "select * from Cars where Цвет like'"+temp+"'";

        if(FilterType.getSelectedIndex()== 7) 
            sql = "select * from Cars where Цена like'"+temp+"'";
        
        if(FilterType.getSelectedIndex()== 8)
            sql = "select * from Cars where Статус like'"+temp+"'";
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtFilterInputKeyReleased

    private void SortTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortTypeActionPerformed
        // TODO add your handling code here:
        String sql=null;
        if(SortType.getSelectedIndex()== 0) 
           sql = "select * from Cars"; 
            
        if(SortType.getSelectedIndex()== 1) 
            sql = "select *  from Cars " + " order by Марка";

        if(SortType.getSelectedIndex()== 2) 
             sql = "select *  from Cars " + " order by Модель";

        if(SortType.getSelectedIndex()== 3) 
          sql = "select *  from Cars " + " order by ГодВыпуска";

        if(SortType.getSelectedIndex()== 4) 
            sql = "select *  from Cars " + " order by ОбъёмДвигателя";

        if(SortType.getSelectedIndex()== 5) 
             sql = "select *  from Cars " + " order by Цвет";

        if(SortType.getSelectedIndex()== 6) 
            sql = "select *  from Cars " + " order by Цена";
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SortTypeActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        Id=jTable1.getModel().getValueAt(row, 0).toString();
        status=jTable1.getModel().getValueAt(row, 14).toString();
        currentStatus.setText(status);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        currentStatus.setVisible(true);
        statusType.setVisible(true);
        DeleteItem.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void DeleteItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteItemMouseClicked
        // TODO add your handling code here:
        //String temp="select ID from Cars";
        String sql = "delete * from Cars where ID=" +Id+ "";
        try{
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Удалено");
            UpdateJTable();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DeleteItemMouseClicked

    private void statusTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTypeActionPerformed
        String tmp = (String) statusType.getSelectedItem();
        String sql= "Update Cars set Статус='"+tmp+"' where ID = "+Id+"";
        try{
            pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Статус изменён");
            currentStatus.setText(tmp);
            UpdateJTable();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_statusTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteItem;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Exit;
    private javax.swing.JComboBox FilterType;
    private javax.swing.JComboBox SortType;
    private javax.swing.JTextField currentStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox statusType;
    private javax.swing.JTextField txtFilterInput;
    // End of variables declaration//GEN-END:variables
}
